### ISSUE TITLE
Refactoring: `lottmapgen`

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#1059]
- [ ] ~поправить подсказки `luacheck` (удалить из `exclude_files` в `.luacheckrc`)~ (вфнесено в [#1084](https://github.com/lord-server/lord/issues/1084))
 - [x] именнованые константы биомов
 - [x] вынести конфиг
 - [ ] #1058
    - [ ] ~вынести генерацию в отдеьный файл~ (вфнесено в [#1084](https://github.com/lord-server/lord/issues/1084))
    - [x] разнести по функциям
        - [x] генерация над поверхностью (airspace)
        - [x] генерация покрытия
        - [x] генерация подземлёй
        - [x] замена воды, камня, песка
        - [x] и пр.
 - [x] добавить замер генерации чанка, вычисление среднего (если указано в конфиге)
 - [ ] speed up:
    - [ ] ~вынести создание статических локальных переменных из ф-ций (`functions.lua`)~ (вфнесено в [#1084](https://github.com/lord-server/lord/issues/1084))
    - [ ] ~использовать залинкованную область памяти для `VoxelManip` (где-то в доках натыкался)~ (вфнесено в [#1084](https://github.com/lord-server/lord/issues/1084))
    - [x] вынести получение ContentID при каждой итерации
    - [x] заменить `math.random` и пр. на локальные

**Comment by alek13** [comment]
остальное вынесено во второй этап #1084
