### ISSUE TITLE
Обновление модов: various/areas

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#1188]
**Info:**
 - https://github.com/minetest-mods/areas
 - все наши исправления тоже сделаны в оригинале
 - дополнительных никаких наших доработок нет

**ToDo:**
 - [x] Fork в lord-server
 - [x] PR с локалью в оргинал (https://github.com/minetest-mods/areas/pull/68)
 - [x] ~подключение сабмодулем (на время принятия PR можно подключть с форка)~ на время ожидания PR был закоммичен перевод (bc534165750bc516a16d64a076e743e6992fa0af, c7e128af707089dbd9c5449f34a02f83b0491b2c)

**Comment by alek13** [comment]
в ожидании https://github.com/minetest-mods/areas/pull/68
