### ISSUE TITLE
Новые камни в пещерах

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#1270]
Предложения от @RayDonnovan :
Хотелось бы видеть в пещерах: 

- [x] #1273 Гранит
- [x] #1279 
- [x] #1280

- [x] #1274 Диорит/`diorite` (Полированный диорит `polished_diorite`)  

![Image](https://user-images.githubusercontent.com/113035903/188897980-f2261e42-4bc3-4232-9ecf-f4de99e377d4.png) ![Image](https://user-images.githubusercontent.com/113035903/188898208-580a55f4-8191-42c9-8f76-5596b43d5aba.png)

- [x] #1271 Андезит/`andesite` (Полированный андезит`polished_andesite`)
![Image](https://user-images.githubusercontent.com/113035903/188898485-89b28476-c8bf-4480-bf50-9830ab2720a0.png) ![Image](https://user-images.githubusercontent.com/113035903/188899482-635f23e1-c2f0-4c68-b72c-4b1dd2cfe9fa.png)

- [x] #1275  Глубинный сланец / `deepslate`, (Колотый глубинный сланец`cobbled_deepslate`  Полированный глубинный сланец`polished_deepslate`) 
![Image](https://user-images.githubusercontent.com/113035903/188900088-1f323015-cfbe-40fe-9d71-d179bf2040bc.png) ![Image](https://user-images.githubusercontent.com/113035903/188900145-d622635e-cc83-44db-ae91-b4b07077618c.png)  ![Image](https://user-images.githubusercontent.com/113035903/188900388-19328d19-c2d7-47be-8434-1bbcc22c35c6.png)

- [x] Кальцит / `calcite` (#1280)
![Image](https://user-images.githubusercontent.com/113035903/188901636-62f683d8-cffe-4e90-8857-c4bf9bc45f33.png)

- [ ] #1277 #1278 Туф / `tuff`
![Image](https://user-images.githubusercontent.com/113035903/188901806-57e8bf13-9f26-4250-b563-0ab946a374bb.png)

- [ ] ~Бедрок / `bedrock`~ (**_ОТКЛОНЕНО_**)
![Image](https://user-images.githubusercontent.com/113035903/188902474-4ab729b0-a907-4589-a579-7023524bf2a3.png)

- [x] #1276 Базальт / `basalt`
![Image](https://user-images.githubusercontent.com/113035903/188903088-cf288553-cdc7-4402-b1ba-2b8f3d71ea19.png)

- [x] Кварцевый блок  / `quartz_block`, (Кварцевые кирпичи `quartz_bricks`, Кварцевая колонна `quartz_pillar`, Резной кварцевый блок `chiseled_quartz_block`) [ИСПОЛЬЗУЙТЕ МРАМОР]
![Image](https://user-images.githubusercontent.com/113035903/188904264-c954546e-83d0-481a-8764-c285b373bd5e.png)  ![Image](https://user-images.githubusercontent.com/113035903/188903806-559f6efd-1562-46e5-9313-e9878ad4c512.png) ![Image](https://user-images.githubusercontent.com/113035903/188903853-573afdaf-0924-4f07-b712-8bea503b864d.png) ![Image](https://user-images.githubusercontent.com/113035903/188903903-fb365713-4022-44ec-aa3b-dcf3b07a064c.png)

- [x]  #1281 Магма / `magma_block`
![Image](https://user-images.githubusercontent.com/113035903/188905488-51113baa-1d16-45c7-861d-809e7f0bcbaf.png)

- [ ]  Белый бетон / `white_concrete`(Светло-серый бетон`light_gray_concrete`, Серый бетон `gray_concrete`, Чёрный бетон `black_concrete`, Коричневый бетон `brown_concrete`) [ОТЛОЖЕНО НА НЕОПР. СРОК]
![Image](https://user-images.githubusercontent.com/113035903/188905814-5a9e5a16-67aa-46a0-a59a-d30eab45e15c.png) ![Image](https://user-images.githubusercontent.com/113035903/188907689-ba1faa5a-07f6-4bfa-8098-a5fabc158e63.png) ![Image](https://user-images.githubusercontent.com/113035903/188906979-0ddb47c0-c6bf-4d34-abf5-88f7b06c0022.png) ![Image](https://user-images.githubusercontent.com/113035903/188907082-43fe16e4-d703-43cd-bd96-334c1abd3b4e.png) ![Image](https://user-images.githubusercontent.com/113035903/188907120-36f94960-05f4-49af-9728-6c30bf2b34be.png)
(Возможно это даже не добыча в пещере а скрещивание определенных пород) 

- [ ]  Белый сухой бетон / `white_concrete_powder` [ОТЛОЖЕНО НА НЕОПР. СРОК]
![Image](https://user-images.githubusercontent.com/113035903/188907974-71e22aff-c937-475c-bdb1-cfb6718ce236.png) ![Image](https://user-images.githubusercontent.com/113035903/188946335-92792c87-dd77-4db2-88e5-d9104a973a99.png) ![Image](https://user-images.githubusercontent.com/113035903/188946378-9990283f-a3d9-4848-b416-1c0e1f461db5.png) ![Image](https://user-images.githubusercontent.com/113035903/188946426-8751c5bc-df0e-4754-81e4-c0ffaf054cb3.png) ![Image](https://user-images.githubusercontent.com/113035903/188946479-956de6c5-f095-4392-8237-c834a15e11b8.png)

- [x] Чернит / `blackstone`  (Золочёный чернит`gilded_blackstone`, Полированный чернит`polished_blackstone`,  Резной полированный чернит`chiseled_polished_blackstone `, Полированно-чернитные кирпичи`polished_blackstone_bricks`, полированно-чернитные кирпичи `cracked_polished_blackstone_bricks `) 
![Image](https://user-images.githubusercontent.com/113035903/188908214-e91e7820-696a-4271-9e8e-63da611a1709.png) ![Image](https://user-images.githubusercontent.com/113035903/188909702-7d91d205-5f06-4441-8abf-860ea5cc42fd.png) ![Image](https://user-images.githubusercontent.com/113035903/188909775-a772f7b1-8e2d-47a5-a034-7c2391145f08.png) ![Image](https://user-images.githubusercontent.com/113035903/188909821-736eb8fd-0fcc-4940-97e1-c59b0fc28f86.png) ![Image](https://user-images.githubusercontent.com/113035903/188909949-049c0e6c-39dc-4e40-bf7e-634c3735304a.png) ![Image](https://user-images.githubusercontent.com/113035903/188909989-c3b72ee8-49b8-4a1d-b922-7782491eb608.png)

- [ ]  Плачущий обсидиан / `crying_obsidian` [ОТЛОЖЕНО НА НЕОПР. СРОК]
![Image](https://user-images.githubusercontent.com/113035903/188909528-b3eeb545-faf4-4ba5-aa7c-4d9506337094.png)

- [x] Каменистая земля / `coarse_dirt`
![Image](https://user-images.githubusercontent.com/113035903/188911700-3755c74b-e4f2-4085-9b93-d635e711cd57.png)

Оставшееся вынесено в #1340

От Van'a. Под проект nord сделал такие (обсидиан, диорит, гранит, андезит):
![Image](https://user-images.githubusercontent.com/82447582/208973900-fc611eeb-253b-4ae0-87f0-6ec5d5e03d5e.png)
Могу скинуть сами текстуры
