### ISSUE TITLE
Clans v2: nickname changes:  use `player_nametag` mod

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#1423]
В нескольких модах используется изменение nametg игрока (напр, в `Player/show_health`).
Нужен общий для всех модоов менеджер:
**blocked by:**
- #1427 

**todo:**
- [x] use `player_nametag`
- [ ] move into separate file
- [x] unify usage
- [x] subscribe & use own callbacks
