### ISSUE TITLE
Протокол XX съезда партии

### ISSUE THREAD

**Issue by narrnika** [lord-server/lord#20]
- [x] 1. определяемся с ядром и выносим моды за скобки [https://github.com/weqqr/lord/issues/19];
- [ ] 2. циркулярку смотрим на Полигоне [https://github.com/minetest-mods/moreblocks];
- [ ] 3. переделываем (настраиваем) гоблинов [https://github.com/FreeLikeGNU/mobs_goblins];
- [ ] 4. выбираем интересных мобов и допиливаем [https://github.com/NPXcoot/nssm];
- [ ] 5. подбираем к ним спавнеры [https://github.com/NPXcoot/nssb];
  
    б. решаем текущие проблемы.

**Comment by TheEagleEye** [comment]
Долго решаем, шустрее над. 7 августа уже.

**Comment by Mikola314** [comment]
"Долго решаем, шустрее над. 7 августа уже." - 
этих трёх пинать:

- [ ] https://github.com/narrnika
- [ ] https://github.com/albel4
- [ ] https://github.com/weqqr
