### ISSUE TITLE
Сталкерские привычки...

### ISSUE THREAD

**Issue by narrnika** [lord-server/lord#21]
... с которыми пора завязывать. Когда в Зоне сталкер глотает бутылку водки не распечатывая и закусывает закрытой же консервой - это ладно, на то и Зона... Но у нас на сервере радиации не наблюдается, так что и желудки у персонажей не мутировавшие.
А значит, надо как нибудь на досуге сделать посуду многоразовой, а не съедаемой вместе с содержимым.
- [x] Миски от еды #98 
- [x] Стаканы от пойла #99
- [x] Бутылки от зелий #100

**Comment by Mikola314** [comment]
Поправка, сталкерская Зона пишется с большой буквы)

**Comment by Mikola314** [comment]
- [ ] Поправить крафт мисок. Сейчас они крафтятся 1 шт. из 3 шт. досок Только яблони. Исправить на 8 шт мисок из 3 досок любой породы дерева.

**Comment by Doloment** [comment]
Можно вопрос. Если в hunger.lua прописать зельки ТОЛЬКО с возвратом тары, что-то выйдет?

**Comment by albel4** [comment]
По идее бутылки от зелий должны быть одноразовыми. Как шприцы. Зелья при смешивании ведут себя не предсказуемо.

**Comment by alek13** [comment]
закрываем, все таски вынесены отдельно
