### ISSUE TITLE
Протокол XXI съезда партии. Формы инвентаря и прочее.

### ISSUE THREAD

**Issue by Mikola314** [lord-server/lord#48]
- [x] 1. Определиться, какие будут меню, какие функции можно ввести в игру как зелья, книги, свитки и т.д. Тем самым избавиться от команд и некоторых кнопок в инвентаре.
- [x] 2. Определиться с общим стилем форм. Какие рамочки, стандартные размеры форм. 
- [x] 3. Определиться, где будем менять фон, а где не будем. Инвентарь, hot-бар, сумки, информационные меню (новости сервера, правила и прочее), книги, листы бумаги, печи, бочки, лабораторки, сундуки, таблички. https://github.com/lord-server/lord/issues/17 
- [ ] 4. Определиться с текстурами кнопок в инвентаре и других формах. Есть смысл сделать кнопки только с иконками, убрав тексты типа "Закрыть". У TheEagleEye есть подборка иконок, рассчитанных на тёмный фон. 
- [x] 5. Определиться со слотами для колец. Они реально нужны.
- [x] 6. Определиться с расположением кнопок и слотов в инвентаре. Шмотка неудачно разложена а форме. (кстати о шмотках https://github.com/lord-server/lord/issues/47 ). Поправить фон под слотами с бронёй, отображением колец на игроке в инвентаре. 
- [x] 7. Определиться с формам информационных меню (новости сервера, правила и прочее) - расположение кнопок и их состав.
- [x] 8. Определиться с формами книг крафта. https://github.com/lord-server/lord/issues/33 как будет выглядеть поиск. 
- [ ] 9. Вспомню - допишу
- [ ] 10. Реализация.

**Comment by narrnika** [comment]
В общем, вот что у меня есть сказать по этому поводу:
https://drive.google.com/open?id=0B1U-1ce_W4WWQ3BDWWx3ekFqLVE
Здесь своего рода демка, наброски, которые ещё надо дорабатывать, но к дефолтной minetest_game прикручивается, можно посмотреть, как работает. Коротко на словах:

- сам мод inventory даёт только механизм вкладок плюс общее оформление (без дополнительных модов по i будет просто пустое окно);
- в других модах, имеющих в depends этот inventory, описываются сами вкладки (имя, лэйбл, список необходимых привилегий, formspec-строка, обработчик событий);
- игрок видит только те вкладки, на которые хватает привилегий;
- сортировка вкладок в списке ведётся по имени, так что для нормального вида имена вкладок начинаются с числового индекса (не очень хорошая идея, но других пока нет)
- номер текущей вкладки каждого игрока хранится в глобальной таблице inventory.current_tabs, так что закрыв/открыв инвентарь, окажешься там же, где и был (в принципе можно завязать на datastorage, хотя не вижу особого смысла...)

Что предполагается в связи с этим делать:
- в модпаке inventory кладём моды, описывающие базовые вкладки инвентаря (крафт, сумки и т.д...);
- lord_info перепахиваем так, что бы новости, правила, справка работали как вкладки; сюда же прикручиваем status;
- lottarmor (и, возможно, lottclothes) перебираем так, что бы предоставляли контент и описывали вкладку для шмота; возможно, на эту же вкладку запихнуть слоты под кольца, тогда имеет смысл собрать в модпак мод-вкладку, мод-с-бронёй, мод-с-одеждой, мод-с-кольцами;
-  lottinventory оставить только на книги крафта (в связи с чем его можно бы и переименовать, чтоб путаницы не было);
- форму по выбору расы/пола/скина (не помню, где оно всё сейчас) оформляем то же как вкладку, при этом для теней будет доступна только эта вкладка (ну, и правила/новости, наверное);
- в идеале сделать несколько административных вкладок, не доступных игрокам: creative-инветарь (или старая команда list), GUI для worldedit'а;

PS Почему именно таблица, а не список или кнопки:
- более пластична, чем кнопки (добавлять/убирать строки проще, чем каждый раз расстояния между кнопками выставлять);
- для кнопок нужны иконки, которые должны быть интуитивно понятны и в то же время хоть немного соответствовать тематике сервера; найти такие затруднительно, а продвинутых дизайнеров/художников среди нас не наблюдается;
- в отличие от простого списка таблица имеет цветовые настройки шрифта, фона, рамок и выделения, так что её можно хоть немного подточить под фоновую текстуру.

**Comment by TheEagleEye** [comment]
Странно тогда как-то получается, моды инклудят инвентарь что-бы выполнить свои функции?
Все таки инвентарь это интерфейс со своим функционал который в себе содержит коллекцию мелких модов или так сказать форм для полной его работоспособности. По сути это тоже самое как extend классов в C++ или Java.

Для наглядности приведу пример игровых интерфейсов ->

**Пример 1:**
Берем книгу с крафтом и разделяем ее по частям.
1. Задний фон.
2. Поле и кнопка поиск.
3. Интерфейс и функционал (мод) крафтинга.
3. Переход по разным станицам (отдельный мод, ему безразлично что сортировать)
4. Сам инвентарь игрока 32 слотов. 8 сверху 24 снизу. (перемещение описывается в нем)

**Пример 2:**
Интерфейс инвентаря мы может разделить следующим образом.
1. Задний фон.
2. Интерфейс и функционал (мод) крафтинга. 
3. Мусорка для удаления предметов. 
4. Одежда игрока со своими слотами. 
5. Сам инвентарь игрока 32 слотов. 8 сверху 24 снизу.

Таким образом если мы хотим изменить инвентарь мы удаляем или присваиваем различные мелкие функции (моды) и пользуемся их функционалом размещая их в главном интерфейсе, но никак не наоборот. 

На данный момент функцию инвентаря выполняет плагин lottarmor (или они вообще раскиданы как-то хаотично). А так же присутствуют какие-то левые плагины инвентаря которые по сути делают совсем другое что им не предназначено делать. 

Да нужно создать один мод инвентаря и дать возможность другим модам хукать его вызовы. Что собственно ты и хотел продемонстрировать?

**Comment by TheEagleEye** [comment]
Кстати да. Мы наверно затронули совсем другую тему. В первом посте как-бы мы хотим определится как будут выглядеть интерфейсы и кто их сможет спроектировать. А теперь мы заходим на часть программирования. 

По моему надо обсуждать что-то одно.

**Comment by Mikola314** [comment]
"А теперь мы заходим на часть программирования." - программную часть я не затрагивал из-за малого опыта. 
9. Вспомню - допишу )

**Comment by narrnika** [comment]
1) "на часть программирования" я зашёл, потому что некоторые вещи проще показать, чем рассказать; кроме того, я неоднократно убеждался, что "проектировать" внешний вид можно сколько угодно, но когда дело доходит до кода, выплывает косяк за косяком, и все первоначальные планы летят на юг, в тёплые страны..
2) "моды инклудят инвентарь что-бы выполнить свое предназначение" - не совсем так; скорее инвентарь то же становится одним из этих модов, и все они запускаются с общей панельки, которая когда-то была инвентарём, а теперь по сути просто фон с набором иконок. Иначе говоря, мод inventory здесь - просто экран с тумблером, к "тумблеру" крепятся остальные моды и выводят всё, что им надо, в рамках "экрана".
3) "По сути это тоже самое как extend классов в C++ или Java" - с c++ знаком очень поверхностно, с java не знаком вообще, так что аналогии не понял.. и да, дабы в дальнейшем не было недопонимания - я не профессиональный программер, так, балуюсь помаленьку.
4) Примеры вышли какие-то не наглядные, лучше бы уж псевдокодом... я так и не понял, откуда взялся "мод крафтинга" и на кой выносить в отдельный мод листалку? в отдельную функцию - куда ни шло, функцию можно в какой-нибудь общий вспомогательный мод а-ля библиотека, но просто отдельный мод... у нас и так их развелось, на мой взгляд, слишком уж много.
5) "А так же присутствуют какие-то левые плагины инвентаря которые по сути делают какие-то странные махинации" - это какие, напомни?

**Comment by narrnika** [comment]
Теперь, собственно по пунктам топика:
1) Все виды телепорта (spawn, home, tp) - на зелья/артефакты; справочники по крафту - в книгах, как и было (хотя книги можно разбить по тематике, а то в общем крафте сейчас дофига чего напихано), можно так же отдельные схемы на листки бумаги с возможностью объединения в книги (но это я уже совсем, пожалуй, размечтался); смену расы/пола/скина - так же не зелья.
2) Общий стиль для системных форм (не привязанных к какому-либо объекту) я предложи как организовать (собственно, в моём варианте будет не общий стиль, а просто одна форма с меняющимся содержимым); с формами объектов (сундуков, печей и иже с ними) сложнее, там по хорошему для каждого объекта свой фон, чтобы не получилось так, что открываешь печь, а она деревянная...
5) Как я уже писал, слоты для колец можно разместить там же, где надевается шмот, при этом выкинув оттуда крафт и мусорку.
8) Лично меня не вдохновляет идея прикручивать поиск к бумажным книгам. Как-то слишком не натурально получается... Саму страницу, вероятно, надо сделать побольше (но не сильно), плюс - разбить книгу общего крафта (или как она там у нас называется) на несколько - "Строительные блоки", "Растениеводство", "Инструмент", "Поваренная книга" и т.д. При этом в некоторых случаях (например с инструментом) можно в книгу вбивать не все крафтсхемы, а принцип построения схемы и список подходящих материалов.

**Comment by albel4** [comment]
Предлагаю примерно такой инвентарь [https://drive.google.com/open?id=0B4xTsOAqpGiAMHNDb2xEb3I4bnM](https://drive.google.com/open?id=0B4xTsOAqpGiAMHNDb2xEb3I4bnM)
Осталось подобрать фон.

**Comment by narrnika** [comment]
> Предлагаю примерно такой инвентарь

У меня два вопроса и одно замечание:
- зачем кнопки "день/ночь", поле Refill игроку, у которого всё равно нет прав на эти действия?
- что делать, когда количество кнопок будет больше 13ти?
- мусорка как кнопка - штука весьма коварная, я бы её оставил только тем, у кого право на креатив-инвентарь есть... ну, или хотя бы убрал подальше, а то порой нехорошо получается...

**Comment by Mikola314** [comment]
"мусорка как кнопка - штука весьма коварная, я бы её оставил только тем, у кого право на креатив-инвентарь есть... ну, или хотя бы убрал подальше, а то порой нехорошо получается..." - полностью поддерживаю)

**Comment by albel4** [comment]
- Кнопки день и ночь может и не нужны вовсе, я просто только для первой придумал пиктограммку. Остальные оставил как есть.
- либо сделать форму шире, либо добавить ещё один ряд. Всё зависит от количества кнопок.
- а кнопка мусорки включает и выключает корзину в форме.

**Comment by TheEagleEye** [comment]
**albel4**, это инвентарь помойка а не инвентарь.

**Comment by Mikola314** [comment]
+ поиск там не работает как надо...

**Comment by albel4** [comment]
TheEagleEye, а я и не говорил, что это окончательный вариант (по-поводу оформления), набросал на скорую руку. Предложи свой вариант.

**Comment by TheEagleEye** [comment]
http://i.imgur.com/LIVOqd3.png - вариант с книгой

**Comment by narrnika** [comment]
"Ответь сначало на вопрос: Что такое инвентарь?" - полагаю, с этим действительно стоит определиться. ИМХО, в контексте текущего обсуждения инвентарь - это форма , которая появляется перед игроком по клавише "i" (на деф.настройках, естественно).

"вариант с книгой" - я так понимаю [А][Б][В][Г]... - это типа алфавитного указателя? в смысле, ссылка для перехода на соотв. позицию? тогда может вынести их наверх/вбок, а-ля закладки?

**Comment by TheEagleEye** [comment]
Если так будет удобней, без вопросов.

**Comment by Mikola314** [comment]
и что дальше?

**Comment by TheEagleEye** [comment]
Нужна иерархия вкладок и расположение всего остального. У кого фантазия хорошо развита, ему и поручить. Как я понимаю у нас кроме редизайна книг, печек, интерфейся, и инвентаря больше ничего нет.

Пока что можно начать перекидывать то что есть на новую платформу. Позже просто подогнать под готовые рисунки. 

А теперь, рекламная пауза http://i.imgur.com/U1Ln4Ww.png - Единственный сервер с таким итерфейсом, есть чем отличиться.

**Comment by Mikola314** [comment]
> http://i.imgur.com/U1Ln4Ww.png - Наверно единственный сервер с таким итерфейсом, есть чем отличиться. При открытие инвентаря кнопки меняют фон на цвета радуги, а так же присутсвует платная кнопка туалета.
не совсем понял

**Comment by albel4** [comment]
> 1. Определиться, какие будут меню, какие функции можно ввести в игру как зелья, книги, свитки и т.д. Тем самым избавиться от команд и некоторых кнопок в инвентаре.
Сюда пишем команды и кнопки в инвентаре от которых хотим избавится (перенести их в объекты игры):
- spawn (зелье)
- sethome
- home

**Comment by TheEagleEye** [comment]
https://lord-interfaces.mybalsamiq.com/projects/lord-interfaces/grid

**Comment by narrnika** [comment]
Э-э-это что? В смысле, это где?

**Comment by TheEagleEye** [comment]
Какая разница, создал для совместного редактирования. Так легче ориентироваться.

**Comment by narrnika** [comment]
Я имею - в чём создал?

**Comment by TheEagleEye** [comment]
Что в чем? Сайт нашел и создал. Онлайн редактирование.

**Comment by narrnika** [comment]
А, если он-лайн редактор, тогда ясно.
По поводу того, что ты уже накидал - варинат 4 весьма сомнителен (в formspec есть элемент "вкладки", и даже с прокруткой, но выглядит он убого), вариант 3 мне дико нравится, сам когда-то такой пытался замутить, но очень уж проблематично сделать так, что б всё выглядело идеально.

**Comment by Mikola314** [comment]
TheEagleEye, кстати о он-лайн редакторах: AVATAN не пробовал?

**Comment by TheEagleEye** [comment]
Зачем мне он если у меня есть Adobe Photoshop CC? Сайт создал что-бы мы вместе могли сохранять и редактировать.

**Comment by Mikola314** [comment]
TheEagleEye, аа.. понятно

**Comment by TheEagleEye** [comment]
Создал дискорд - https://discord.gg/EVYW9NA

Заходите, там поболтаем.

**Comment by Mikola314** [comment]
Отсортировал пару неплохих вариантов 
скелет: 
https://lord-interfaces.mybalsamiq.com/projects/lord-interfaces/Narrnika
оформление: 
http://img.hexus.net/v2/gaming/screenshots_pc/lcck/lcck_large_1.jpg
http://allodspics.rambleon.ru/data/2011-10-30/fantasi-game.jpg
https://s-media-cache-ak0.pinimg.com/564x/c1/91/bf/c191bfa295b7cb569926932bcc7bb30d.jpg
книги:
https://lord-interfaces.mybalsamiq.com/projects/lord-interfaces/book_layout
лист:
http://basel.ucoz.ru/_ph/3/2/853150703.jpg 
Книгу и лист сделать немного темнее

**Comment by Mikola314** [comment]
TheEagleEye , есть продвижения?
