### ISSUE TITLE
Протокол XXII съезда партии: L.O.R.D 2 roadmap

### ISSUE THREAD

**Issue by weqqr** [lord-server/lord#52]
- [ ] Удаление костылей для совместимости со старыми версиями (@weqqr) #93 
- [ ] #48 (Протокол XXI съезда. Формы инвентаря и прочее.)
  - [x] Книги крафта + #33 (поиск)
  - [ ] Фоны [[Unified forms views](https://github.com/lord-server/lord/projects/2)]
  - [ ] Информационные меню (/list, /info etc)
  - [ ] Новый инвентарь
- [x] 32x текстуры (@Mikola314) #97 
- [ ] Унифицировать API для нод (@weqqr) #95 
- [ ] Перенос кодовой базы с самодельных велосипедов на новые функции Minetest (@weqqr) #94 
- [ ] Флаги для areas (@weqqr) #96 
- [ ] Обновление модов до последних версий (???)
- [ ] Мобы, сделанные по-человечески (???)
- [x] ???
- [ ] PROFIT

**Comment by Mikola314** [comment]
По поводу флагов areas. Видел их. Не впечатлили... С учётом того, что они только на углах и фиг видны в наших условиях, не вижу в них смысла. 
Как я понял мы не обираемся давать права areas игрокам.

**Comment by weqqr** [comment]
Я имею ввиду подобную систему
http://minecraft-ru.gamepedia.com/WorldGuard/Флаг

**Comment by Mikola314** [comment]
"Обновление модов до последних версий"
- [ ] Факела из minetest_game 0,4,15 (моделька и метод размещения). 
Красивая модель огня ( Х, а не # как в lord сейчас)
- [ ] Модель, звуки и, возможно, алгоритм движения с поправкой на паровые двигатели
- [ ] Новые библиотеки для локализации. https://github.com/minetest-mods/intllib .
- [ ] Есть информация, что обновился мод ambience .

Добавление модов 
- [ ] mobs_water Предложение от Elrick . Взлетат, но надо подгонять под наши нужды.

**Comment by Doloment** [comment]
Нашел мод на добавление. https://forum.minetest.net/viewtopic.php?f=11&t=17847&hilit=bag - замена нашим сумкам.

**Comment by alek13** [comment]
не актуальна
